### PR TITLE
Feature/filter dashboard nodes

### PR DESCRIPTION
**Pull request by arbulu89**
Filter properly the netweaver nodes in the grafana dashboard to only show the cluster members.
Besides that
- I have updated the HANA dashboard to only have the option to select nodes with a HANA db installed and filter properly the other multicheck boxes.
- I have fixed the systemd units filter to have more precision (otherwise some systemd units like fsck with some files with hana in their name were shown).

As a comment, the `node_exporter` data is shown only for the nodes in the HA cluster. If we want to keep the 4 netweaver cluster in the panel and only show the HA data for the nodes having this exporter we will need to do changes.

https://github.com/SUSE/ha-sap-terraform-deployments/issues/301

@stefanotorresi @MalloZup Temporary dashboard available in http://10.162.31.160

PD: And finally, a small bugfix for qa_mode in `repos.sls`

### CODE REVIEW

**Comment by MalloZup** [comment]
@arbulu89 thx for pr can we have a screenshot?

**Comment by arbulu89** [comment]
image
image
image

**Comment by stefanotorresi** [comment]
> As a comment, the `node_exporter` data is shown only for the nodes in the HA cluster. If we want to keep the 4 netweaver cluster in the panel and only show the HA data for the nodes having this exporter we will need to do changes.

I think this is how it should be. The HA Cluster dashboard is supposed to show details about a Pacemaker cluster, and only two of the Netweaver nodes apply.

**Comment by arbulu89** [comment]
After internal discussion with @stefanotorresi , we have agreed that the current solution is not what we want. We want to still have the `node_exporter` data in the multi cluster dashboard, and only filter the nodes in the detailed HA dashboad, to avoid having non HA nodes to be selected.

**Comment by arbulu89** [comment]
@stefanotorresi I have added the changes for:
1. Only show the nodes if the export HA metrics in the `Node` multi select option
2. Fix a pattern in the `Resource` table that was adding more metrics than the expected ones

As commented, the unique drawback is that if the ha exporter is not working, we won't see and choose the nodes (what I think is good) in that multi select.

**Pull request merged**
