### PR TITLE
Grafana/dashboard: Add initial process table for netweaver

### PR DESCRIPTION
**Pull request by MalloZup**
# What does this PR?

- this pr add an initial dashboard + Process table of process.
- It add also the needed grafana variables like `node_name` etc which we use in other dashboards etc

### CODE REVIEW

**Comment by stefanotorresi** [comment]
@MalloZup do you have a live deployment of this dashboard?

**Comment by MalloZup** [comment]
@stefanotorresi it was the dashboard I showcased on the live-demo

I think right now we can merge it as minimal step. I will try to deploy a new netweaver cluster right now

**Comment by stefanotorresi** [comment]
I'm not sure about the node switcher, though, which was not in the demo yesterday. :wink:
We have to decide if we want the dashboard to present info of all the nodes, akin to what we do with the multi-cluster dashboard: in that case, we don't need any variable switch.

**Comment by MalloZup** [comment]
ok removed please check thx! now is only a minimal graph which we can change later. 
It is only a skeleton right no

**Pull request merged**
