### PR TITLE
Fix VM name on all Cloud providers

### PR DESCRIPTION
**Pull request by ldevulder**
Fix a regression that appears during the last GCE refactoring...

EDIT: fixed for all provider

### CODE REVIEW

**Comment by ldevulder** [comment]
> Anyway, is this not causing the same issue in Azure and AWS?

We could add the same kind of name to Azure and AWS. It's done at that time. It's needed on GCE because the `hostname` variable in `salt_provisioner.tf` is used by GCE to setup the hostname inside the OS, but it's not used like this in Azure and AWS.

But if you think it's more consistent to have the same for all provider I'm OK for this also!

**Comment by ldevulder** [comment]
@arbulu89 I will do the modifications also for Azure and AWS (and test  it!).

**Comment by arbulu89** [comment]
> @arbulu89 I will do the modifications also for Azure and AWS (and test it!).

Thanks @ldevulder It might solve some potential issues in the future

**Comment by ldevulder** [comment]
Tested with success on AWS, I'm updating the PR.

**Comment by ldevulder** [comment]
This PR should be OK.

**Comment by ldevulder** [comment]
@arbulu89 ok, I will merge this PR and will check what you suggest for another PR.

**Pull request merged**
