### PR TITLE
Disable loki package and promtail configuration for sap-blue-horizon

### PR DESCRIPTION
**Pull request by Simranpal**
With this PR, the `loki` and `promtail` configuration is disabled for the `sap-blue-horizon `branch. It is because the package is not available from official SUSE repositories and package.

I have commented the code related to `loki` and `promtail`.

### CODE REVIEW

**Review by MalloZup — APPROVED** [review]
thx

**Review by arbulu89 — COMMENTED** [review]
@Simranpal @MalloZup 
For me this change it botched job. The previous comments were `jinja` syntax comments, and this is jinja code.
In any case, we need to think how to deal with this.
I'm in favor do removing totally, and creating a new branch `loki`, where this changes are stored, and doesn't belong to `develop` or `master`

**Comment by MalloZup** [comment]
ok for removal to me also

**Comment by Simranpal** [comment]
@arbulu89 @MalloZup i commented to use reference for future changes.
I am not sure if we should freeze this, or I update the PR to remove the relevant code.

**Comment by MalloZup** [comment]
@Simranpal  remove the code and then we can merge this pr

**Comment by Simranpal** [comment]
@MalloZup thanks, I removed the used code. The loki.sls and promtail template still remain, but they are not used.

**Review by arbulu89 — APPROVED** [review]

**Pull request merged**
