### PR TITLE
Terraform v1.0.8

### PR DESCRIPTION
**Pull request by yeoldegrove**
* update terraform to v1.0.8 and plugins to latest available versions
  * providers/versions are now maintained in these files `providers.tf` and `.terraform.lock.hcl` (https://www.terraform.io/docs/language/dependency-lock.html)
  * format changes for terraform v1.0.8
* azure: argument azurerm_lb_backend_address_pool.resource_name is deprecated
* openstack: changes needed for terraform v1.0.8 and openstack provider v1.44.0 updates
* ci
  * ci: update terraform to v1.0.8
  * ci: remove terraform-provider-libvirt which is now available via https://registry.terraform.io/

### CODE REVIEW

**Comment by yeoldegrove** [comment]
Merge will be done after terraform v1.0.8 is released on openSUSE Tumbleweed.

**Comment by ricardobranco777** [comment]
> Merge will be done after terraform v1.0.8 is released on openSUSE Tumbleweed.

1.1.3 is now available at
https://download.opensuse.org/repositories/systemsmanagement:/terraform/openSUSE_Tumbleweed/x86_64/

**Comment by yeoldegrove** [comment]
I will refactor this again to support terraform 1.1.x and will update the PR.

**Comment by melzer-b1** [comment]
this PR is obsoleted by #818
changes of this PR are considered

**Comment by yeoldegrove** [comment]
obsoleted by #818

**Pull request closed without merging**
