### PR TITLE
Feature/public ssh key

### PR DESCRIPTION
**Pull request by arbulu89**
Currently we need to copy the public key string. This is quite annoying.

I have updated how this parameter is used to use the path instead the content (this is already done this way in GCP)

### CODE REVIEW

**Comment by juadk** [comment]
Good point, tested today with your branch feature/azure_salt and it works.

**Comment by arbulu89** [comment]
> LGTM.
> 
> It would be nice to use the same variables (for SSH at least) across _all_ providers. GCP uses `ssh_key_file` & `ssh_pub_key_file`.

Agree. I didn't touch this because I have not used GCP yet. But if you agree I can change all of them. In fact `libvirt` uses other name too

**Comment by ricardobranco777** [comment]
> > LGTM.
> > It would be nice to use the same variables (for SSH at least) across _all_ providers. GCP uses `ssh_key_file` & `ssh_pub_key_file`.
> 
> Agree. I didn't touch this because I have not used GCP yet. But if you agree I can change all of them. In fact `libvirt` uses other name too

Of course.  Better now than never... :)

**Comment by arbulu89** [comment]
> > > LGTM.
> > > It would be nice to use the same variables (for SSH at least) across _all_ providers. GCP uses `ssh_key_file` & `ssh_pub_key_file`.
> > 
> > 
> > Agree. I didn't touch this because I have not used GCP yet. But if you agree I can change all of them. In fact `libvirt` uses other name too
> 
> Of course. Better now than never... :)

@ricardobranco777 Names updated in all providers. Now all of them are using the same naming (even libvirt)

**Comment by ricardobranco777** [comment]
> > > > LGTM.
> > > > It would be nice to use the same variables (for SSH at least) across _all_ providers. GCP uses `ssh_key_file` & `ssh_pub_key_file`.
> > > 
> > > 
> > > Agree. I didn't touch this because I have not used GCP yet. But if you agree I can change all of them. In fact `libvirt` uses other name too
> > 
> > 
> > Of course. Better now than never... :)
> 
> @ricardobranco777 Names updated in all providers. Now all of them are using the same naming (even libvirt)

Now fix the Travis check :)

**Comment by juadk** [comment]
LGTM, thanks @arbulu89

**Comment by arbulu89** [comment]
@alvarocarvajald @hsehic I don't want to create any pressure, but could you have a look on this PR? This PR is blocking some of my other tasks, and the changes are quite trivial, so it shouldn't take long to check it.

Many thanks in advance!

**Comment by hsehic** [comment]
LGTM

**Pull request merged**
