### PR TITLE
add shellcheck to CI and apply fixes to provision.sh

### PR DESCRIPTION
**Pull request by stefanotorresi**
https://github.com/koalaman/shellcheck is awesome, but wtf, we're still using shell. :rofl:

### CODE REVIEW

**Review by arbulu89 — APPROVED** [review]
@stefanotorresi Thanks

I guess that it only adds the check and the recommended changes, right?
Without any change in the behavour

**Comment by stefanotorresi** [comment]
exactly, they were mostly mitigation for common shell scripting traps like variable quoting and such.

**Review by MalloZup — APPROVED** [review]
thx ! yeah we should substitute bash to golang code imho but ok another story in another context.

**Comment by stefanotorresi** [comment]
@MalloZup I was just joking, man!! :grimacing:

**Pull request merged**
