### PR TITLE
Handle case where srv/salt already exists

### PR DESCRIPTION
**Pull request by MalloZup**
In azure deployment with sle15sp2 image we have failure otherwise

### CODE REVIEW

**Review by arbulu89 — CHANGES_REQUESTED** [review]
@MalloZup I have checked this issue, and I have found out something quite interesting.
It looks like that not only salt is installed by default in `SLE15 SP2`, even our `salt-shaptools` and formulas are installed. That's why the `mv` operations files, becauese `_modules` and `_states` folders are already there in `/srv/salt`.

For this reason, it looks quite risky to remove `/srv/salt` folder, because it will remove folder from one of our packages.

I think we need something better

**Comment by arbulu89** [comment]
Something like this should work: 
```
mkdir -p /srv/salt
    cp -R /tmp/salt/* /srv/salt || true
    rm -rf /tmp/salt
    mkdir -p /srv/pillar
    cp -R /tmp/pillar/* /srv/pillar || true
    rm -rf /tmp/pillar
```

**Comment by MalloZup** [comment]
ok adapted. I will test the patch on azure
do we know why shaptools are already installed out of curiosity?

**Comment by MalloZup** [comment]
ok last change suggested works on azure @arbulu89

**Comment by arbulu89** [comment]
> ok adapted. I will test the patch on azure
> do we know why shaptools are already installed out of curiosity?

To have the monitoring packages running apparently

**Review by arbulu89 — APPROVED** [review]

**Pull request merged**
