### PR TITLE
fixing typo, improving NetWeaver and S/4HANA password comment

### PR DESCRIPTION
**Pull request by pirat013**
- changing the password comment to be more specific to avoid failing installation due to invalid password combinations
- comment implemented for all infrastructures

### CODE REVIEW

**Review by diegoakechi — APPROVED** [review]
Nice touch @pirat013 !

**Review by diegoakechi — CHANGES_REQUESTED** [review]
... but I think you need push it to the `develop` branch... lets see what @arbulu89 thinks..

**Review by arbulu89 — CHANGES_REQUESTED** [review]
More or less improve this: https://github.com/SUSE/ha-sap-terraform-deployments/pull/689
As @diegoakechi said, submit the PR to develop (you don't need to close and open a new one, you can edit this PR).
And add the same documentation to openstack if you can please

**Comment by yeoldegrove** [comment]
@arbulu89 this is good to merge

**Comment by arbulu89** [comment]
Hi @yeoldegrove , I would like to add the same new entry in the openstack terraform.tfvars.example, could you add it?

**Comment by yeoldegrove** [comment]
> Hi @yeoldegrove , I would like to add the same new entry in the openstack terraform.tfvars.example, could you add it?

@arbulu89 done

**Review by arbulu89 — APPROVED** [review]

**Pull request merged**
