### PR TITLE
Fix fencing on GCE with onoff method

### PR DESCRIPTION
**Pull request by ldevulder**
Add a location constraint for fence_gce stronith resource.

The resource must *NOT* run on the same node it has to managed!

Because the agent has to stop and start the node, so if it runs on the same node it cannot do the start command, and so the node cannot be restarted.

Manually tested.

Command used to test the fencing: `crm node fence <node>`, a sysrq command can also be used to simulate a crash on the node.

Related bug: https://bugzilla.suse.com/show_bug.cgi?id=1182701

*NOTE:* I forget to add that this issue happens in newer versions of `fence_gce` available in SLE 15-SP3, no issue until now on previous version.

### CODE REVIEW

**Review by stefanotorresi — COMMENTED** [review]
LGTM. Do we need to document this somehow, or is it documented upstream already?

**Comment by ldevulder** [comment]
> Do we need to document this somehow, or is it documented upstream already?

The only documentation I found is the one on [GCP website](https://cloud.google.com/solutions/sap/docs/sap-hana-ha-config-sles#create_the_stonith_primitive_resources), but as you can see it's not up to date as it still uses `gcpstonith` agent...

The [RHEL one](https://cloud.google.com/solutions/sap/docs/sap-hana-ha-config-rhel#set_up_fencing) is better, with a pretty good example how to use `fence_gce`. The only difference is that in the 2 nodes example they force the execution of the STONITH agent in the opposite node with a constraint location. What I did is an easier configuration and can work on more than 2 nodes. but at the end it's the same behavior: the STONITH agent for a node shouldn't run on it.

So I think that the official GCP doc have to be changed, but I don't know who have to ask/do this. @ab-mohamed maybe you know?

**Comment by ldevulder** [comment]
Any chance to have this merged/fixed? The v7 version will have to issue also without this PR ;-)

**Comment by ab-mohamed** [comment]
Hi, 

@ldevulder

Even without any `location` constraints, all the fencing resources will be registered with the fenced daemon on every node, meaning every node is able to be assigned to perform fencing targeting any nodes, which usually is the preferred way.

@gao-yan: any other insights? 

Best regards,
Ab

**Comment by gao-yan** [comment]
Whether/where a fencing resource shown running with crm_mon only indicates whether/where the fencing resource is being monitored. And it doesn't mean fencing can be only issued from there. SBD is the example.

So unless GCP API has such a limitation, location constraint doesn't really offer anything.

What exactly is the issue in the test? Fencing is not issued or failed?

I'd expect fencing is still issued from the other node and succeeds.

**Comment by ab-mohamed** [comment]
Here are my testing results:

The cluster configurations are:
```
node 1: default-hana01 \
        attributes lpa_prd_lpt=1614688124 hana_prd_vhost=default-hana01 hana_prd_site=NUE hana_prd_op_mode=logreplay hana_prd_srmode=sync hana_prd_remoteHost=default-hana02
node 2: default-hana02 \
        attributes lpa_prd_lpt=30 hana_prd_op_mode=logreplay hana_prd_vhost=default-hana02 hana_prd_remoteHost=default-hana01 hana_prd_site=FRA hana_prd_srmode=sync
# SAP HANA resources
primitive rsc_SAPHanaTopology_PRD_HDB00 ocf:suse:SAPHanaTopology \
        params SID=PRD InstanceNumber=00 \
        op monitor interval=10 timeout=600 \
        op start interval=0 timeout=600 \
        op stop interval=0 timeout=300
primitive rsc_SAPHana_PRD_HDB00 ocf:suse:SAPHana \
        params SID=PRD InstanceNumber=00 PREFER_SITE_TAKEOVER=True AUTOMATED_REGISTER=False DUPLICATE_PRIMARY_TIMEOUT=7200 \
        op start interval=0 timeout=3600 \
        op stop interval=0 timeout=3600 \
        op promote interval=0 timeout=3600 \
        op monitor interval=60 role=Master timeout=700 \
        op monitor interval=61 role=Slave timeout=700
# Platform dependant (stonith, virtual ip address, cib options, etc) resource
# This stonith resource will be duplicated for each node in the cluster
primitive rsc_gcp_stonith_PRD_HDB00_default-hana01 stonith:fence_gce \
        params plug=default-hana01 pcmk_host_map="default-hana01:default-hana01" \
        meta target-role=Started
# Platform dependant (stonith, virtual ip address, cib options, etc) resource
# This stonith resource will be duplicated for each node in the cluster
primitive rsc_gcp_stonith_PRD_HDB00_default-hana02 stonith:fence_gce \
        params plug=default-hana02 pcmk_host_map="default-hana02:default-hana02" \
        meta target-role=Started
primitive rsc_gcp_vip_PRD_HDB00 gcp-vpc-move-route \
        params ip=10.0.1.12 vpc_network=default-network route_name=default-hana-route \
        op start interval=0 timeout=180 \
        op stop interval=0 timeout=180 \
        op monitor interval=60 timeout=60
ms msl_SAPHana_PRD_HDB00 rsc_SAPHana_PRD_HDB00 \
        meta clone-max=2 clone-node-max=1 interleave=true
clone cln_SAPHanaTopology_PRD_HDB00 rsc_SAPHanaTopology_PRD_HDB00 \
        meta is-managed=true clone-node-max=1 interleave=true
colocation col_saphana_ip_PRD_HDB00 2000: rsc_gcp_vip_PRD_HDB00:Started msl_SAPHana_PRD_HDB00:Master
order ord_SAPHana_PRD_HDB00 Optional: cln_SAPHanaTopology_PRD_HDB00 msl_SAPHana_PRD_HDB00
property SAPHanaSR: \
        hana_prd_site_srHook_FRA=SOK
property cib-bootstrap-options: \
        have-watchdog=false \
        dc-version="2.0.4+20200616.2deceaa3a-3.3.1-2.0.4+20200616.2deceaa3a" \
        cluster-infrastructure=corosync \
        cluster-name=hana_cluster \
        stonith-enabled=true
rsc_defaults rsc-options: \
        resource-stickiness=1000 \
        migration-threshold=5000
op_defaults op-options: \
        timeout=600 \
        record-pending=true
```

`default-hana01` is the current primary HANA and `default-hana02` is the secondary:
```
default-hana01:~ # crm_mon -rnf1
Cluster Summary:
  * Stack: corosync
  * Current DC: default-hana01 (version 2.0.4+20200616.2deceaa3a-3.3.1-2.0.4+20200616.2deceaa3a) - partition with quorum
  * Last updated: Tue Mar  2 12:26:49 2021
  * Last change:  Tue Mar  2 12:26:38 2021 by root via crm_attribute on default-hana01
  * 2 nodes configured
  * 7 resource instances configured

Node List:
  * Node default-hana01: online:
    * Resources:
      * rsc_SAPHanaTopology_PRD_HDB00	(ocf::suse:SAPHanaTopology):	 Started
      * rsc_gcp_stonith_PRD_HDB00_default-hana01	(stonith:fence_gce):	 Started
      * rsc_SAPHana_PRD_HDB00	(ocf::suse:SAPHana):	 Master
      * rsc_gcp_vip_PRD_HDB00	(ocf::heartbeat:gcp-vpc-move-route):	 Started
  * Node default-hana02: online:
    * Resources:
      * rsc_SAPHana_PRD_HDB00	(ocf::suse:SAPHana):	 Slave
      * rsc_SAPHanaTopology_PRD_HDB00	(ocf::suse:SAPHanaTopology):	 Started
      * rsc_gcp_stonith_PRD_HDB00_default-hana02	(stonith:fence_gce):	 Started

Inactive Resources:
  * No inactive resources

Migration Summary:
```

`rsc_gcp_stonith_PRD_HDB00_default` is working on `default-hana01` and the `rsc_gcp_stonith_PRD_HDB00_default-hana02` is working on `default-hana02`.

Everything is OK:
```
default-hana02:~ # SAPHanaSR-showAttr 
Global cib-time                 
--------------------------------
global Tue Mar  2 12:26:38 2021 

Resource                      is-managed 
-----------------------------------------
cln_SAPHanaTopology_PRD_HDB00 true       

Sit srHook 
-----------
FRA SOK    

Hosts          clone_state lpa_prd_lpt node_state op_mode   remoteHost     roles                            score site srmode sync_state version                vhost          
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default-hana01 PROMOTED    1614687998  online     logreplay default-hana02 4:P:master1:master:worker:master 150   NUE  sync   PRIM       2.00.046.00.1581325702 default-hana01 
default-hana02 DEMOTED     30          online     logreplay default-hana01 4:S:master1:master:worker:master 100   FRA  sync   SOK        2.00.046.00.1581325702 default-hana02 
```

So, I initiated the feist fencing action:
```
default-hana01:~ # crm node fence default-hana02
Fencing default-hana02 will shut down the node and migrate any resources that are running on it! Do you want to fence default-hana02 (y/n)? y
```

The logs messages were fine:
```
Mar 02 12:32:27 default-hana01 pacemaker-attrd[18415]:  notice: Setting terminate[default-hana02]: (unset) -> true
Mar 02 12:32:27 default-hana01 pacemaker-controld[18417]:  notice: State transition S_IDLE -> S_POLICY_ENGINE
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  warning: Cluster node default-hana02 will be fenced: termination was requested
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  warning: Node default-hana02 is unclean
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  warning: Scheduling Node default-hana02 for STONITH
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  notice:  * Fence (reboot) default-hana02 'termination was requested'
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  notice:  * Stop       rsc_SAPHana_PRD_HDB00:1                      (           Slave default-hana02 )   due to node availability
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  notice:  * Stop       rsc_SAPHanaTopology_PRD_HDB00:1              (                 default-hana02 )   due to node availability
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  notice:  * Move       rsc_gcp_stonith_PRD_HDB00_default-hana02     ( default-hana02 -> default-hana01 )
Mar 02 12:32:27 default-hana01 pacemaker-schedulerd[18416]:  warning: Calculated transition 30 (with warnings), saving inputs in /var/lib/pacemaker/pengine/pe-warn-0.bz2
Mar 02 12:32:27 default-hana01 pacemaker-controld[18417]:  notice: Processing graph 30 (ref=pe_calc-dc-1614688347-72) derived from /var/lib/pacemaker/pengine/pe-warn-0.bz2
Mar 02 12:32:27 default-hana01 pacemaker-controld[18417]:  notice: Requesting fencing (reboot) of node default-hana02
Mar 02 12:32:27 default-hana01 pacemaker-controld[18417]:  notice: Initiating start operation rsc_gcp_stonith_PRD_HDB00_default-hana02_start_0 locally on default-hana01
Mar 02 12:32:27 default-hana01 pacemaker-fenced[18413]:  notice: Client pacemaker-controld.18417.63dadb7e wants to fence (reboot) 'default-hana02' with device '(any)'
Mar 02 12:32:27 default-hana01 pacemaker-fenced[18413]:  notice: Requesting peer fencing (reboot) targeting default-hana02
Mar 02 12:32:27 default-hana01 pacemaker-execd[18414]:  notice: executing - rsc:rsc_gcp_stonith_PRD_HDB00_default-hana02 action:start call_id:37
Mar 02 12:32:27 default-hana01 pacemaker-fenced[18413]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana01 is not eligible to fence (reboot) default-hana02: static-list
Mar 02 12:32:27 default-hana01 pacemaker-fenced[18413]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana02 is eligible to fence (reboot) default-hana02: static-list
Mar 02 12:32:27 default-hana01 pacemaker-fenced[18413]:  notice: Requesting that default-hana01 perform 'reboot' action targeting default-hana02
Mar 02 12:32:27 default-hana01 pacemaker-fenced[18413]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana01 is not eligible to fence (reboot) default-hana02: static-list
Mar 02 12:32:27 default-hana01 pacemaker-fenced[18413]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana02 is eligible to fence (reboot) default-hana02: static-list
Mar 02 12:32:29 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana02 start (call 37) exited with status 0 (execution time 1167ms, queue time 0ms)
Mar 02 12:32:29 default-hana01 pacemaker-controld[18417]:  notice: Result of start operation for rsc_gcp_stonith_PRD_HDB00_default-hana02 on default-hana01: ok
```

Now, the cluster is up and running again:
```
default-hana01:~ # crm_mon -rnf1
Cluster Summary:
  * Stack: corosync
  * Current DC: default-hana01 (version 2.0.4+20200616.2deceaa3a-3.3.1-2.0.4+20200616.2deceaa3a) - partition with quorum
  * Last updated: Tue Mar  2 12:35:21 2021
  * Last change:  Tue Mar  2 12:34:21 2021 by root via crm_attribute on default-hana02
  * 2 nodes configured
  * 7 resource instances configured

Node List:
  * Node default-hana01: online:
    * Resources:
      * rsc_SAPHanaTopology_PRD_HDB00	(ocf::suse:SAPHanaTopology):	 Started
      * rsc_gcp_stonith_PRD_HDB00_default-hana01	(stonith:fence_gce):	 Started
      * rsc_SAPHana_PRD_HDB00	(ocf::suse:SAPHana):	 Master
      * rsc_gcp_vip_PRD_HDB00	(ocf::heartbeat:gcp-vpc-move-route):	 Started
      * rsc_gcp_stonith_PRD_HDB00_default-hana02	(stonith:fence_gce):	 Started
  * Node default-hana02: online:
    * Resources:
      * rsc_SAPHana_PRD_HDB00	(ocf::suse:SAPHana):	 Slave
      * rsc_SAPHanaTopology_PRD_HDB00	(ocf::suse:SAPHanaTopology):	 Started

Inactive Resources:
  * No inactive resources

Migration Summary:
```
```
default-hana02:~ # SAPHanaSR-showAttr 
Global cib-time                 
--------------------------------
global Tue Mar  2 12:35:24 2021 

Resource                      is-managed 
-----------------------------------------
cln_SAPHanaTopology_PRD_HDB00 true       

Sit srHook 
-----------
FRA SOK    

Hosts          clone_state lpa_prd_lpt node_state op_mode   remoteHost     roles                            score site srmode sync_state version                vhost          
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default-hana01 PROMOTED    1614688524  online     logreplay default-hana02 4:P:master1:master:worker:master 150   NUE  sync   PRIM       2.00.046.00.1581325702 default-hana01 
default-hana02 DEMOTED     30          online     logreplay default-hana01 4:S:master1:master:worker:master 100   FRA  sync   SOK        2.00.046.00.1581325702 default-hana02 
```

Notice that the `rsc_gcp_stonith_PRD_HDB00_default-hana01` and `rsc_gcp_stonith_PRD_HDB00_default-hana02` are working now on the same node.

Now, I am going to fence `default-hana01` from `default-hana02`:
```
default-hana02:~ # crm node fence default-hana01
Fencing default-hana01 will shut down the node and migrate any resources that are running on it! Do you want to fence default-hana01 (y/n)? y
```

The logs messages were good:
```
Mar 02 12:37:01 default-hana02 pacemaker-attrd[1944]:  notice: Setting terminate[default-hana01]: (unset) -> true
Mar 02 12:37:01 default-hana02 pacemaker-fenced[1942]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana01 is eligible to fence (reboot) default-hana01: static-list
Mar 02 12:37:01 default-hana02 pacemaker-fenced[1942]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana02 is not eligible to fence (reboot) default-hana01: static-list
Mar 02 12:37:01 default-hana02 pacemaker-execd[1943]:  notice: executing - rsc:rsc_gcp_stonith_PRD_HDB00_default-hana01 action:start call_id:29
Mar 02 12:37:01 default-hana02 pacemaker-execd[1943]:  notice: executing - rsc:rsc_gcp_stonith_PRD_HDB00_default-hana02 action:start call_id:30
Mar 02 12:37:01 default-hana02 pacemaker-fenced[1942]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana01 is eligible to fence (reboot) default-hana01: static-list
Mar 02 12:37:01 default-hana02 pacemaker-fenced[1942]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana02 is not eligible to fence (reboot) default-hana01: static-list
Mar 02 12:37:03 default-hana02 pacemaker-execd[1943]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana01 start (call 29) exited with status 0 (execution time 1156ms, queue time 0ms)
Mar 02 12:37:03 default-hana02 pacemaker-controld[1946]:  notice: Result of start operation for rsc_gcp_stonith_PRD_HDB00_default-hana01 on default-hana02: ok
Mar 02 12:37:03 default-hana02 pacemaker-execd[1943]:  notice: rsc_gcp_stonith_PRD_HDB00_default-hana02 start (call 30) exited with status 0 (execution time 1545ms, queue time 0ms)
Mar 02 12:37:03 default-hana02 pacemaker-controld[1946]:  notice: Result of start operation for rsc_gcp_stonith_PRD_HDB00_default-hana02 on default-hana02: ok
Mar 02 12:37:11 default-hana02 su[17604]: (to prdadm) root on none
Mar 02 12:37:11 default-hana02 su[17728]: (to prdadm) root on none
Mar 02 12:37:12 default-hana02 su[17834]: (to prdadm) root on none
Mar 02 12:37:13 default-hana02 SAPHanaTopology(rsc_SAPHanaTopology_PRD_HDB00)[17939]: INFO: DEC: site=FRA, mode=sync, MAPPING=default-hana01, hanaRemoteHost=default-hana01
Mar 02 12:37:13 default-hana02 SAPHanaTopology(rsc_SAPHanaTopology_PRD_HDB00)[17954]: INFO: RA ==== begin action monitor_clone (0.154.0) ====
Mar 02 12:37:13 default-hana02 su[18000]: (to prdadm) root on none
Mar 02 12:37:14 default-hana02 SAPHanaTopology(rsc_SAPHanaTopology_PRD_HDB00)[18152]: INFO: RA ==== end action monitor_clone with rc=0 (0.154.0) (3s)====
Mar 02 12:37:14 default-hana02 pacemaker-fenced[1942]:  notice: Operation 'reboot' [17569] (call 5 from pacemaker-controld.18417) for host 'default-hana01' with device 'rsc_gcp_stonith_PRD_HDB00_default-hana01' returned: 0 (OK)
```

Now, I have to register `default-hana01`:
```
default-hana01:~ # su - prdadm
prdadm@default-hana01:/usr/sap/PRD/HDB00> hdbnsutil -sr_register --remoteHost=default-hana02 --remoteInstance=00 --replicationMode=sync --operationMode=logreplay --name=NUE
```

And refresh the `SAPHana` RA:
```
default-hana01:~ # crm resource refresh rsc_SAPHana_PRD_HDB00
```

The cluster is up and running again now:
```
default-hana02:~ # crm_mon -rnf1
Cluster Summary:
  * Stack: corosync
  * Current DC: default-hana02 (version 2.0.4+20200616.2deceaa3a-3.3.1-2.0.4+20200616.2deceaa3a) - partition with quorum
  * Last updated: Tue Mar  2 12:46:20 2021
  * Last change:  Tue Mar  2 12:46:10 2021 by root via crm_attribute on default-hana01
  * 2 nodes configured
  * 7 resource instances configured

Node List:
  * Node default-hana01: online:
    * Resources:
      * rsc_SAPHanaTopology_PRD_HDB00	(ocf::suse:SAPHanaTopology):	 Started
      * rsc_SAPHana_PRD_HDB00	(ocf::suse:SAPHana):	 Slave
  * Node default-hana02: online:
    * Resources:
      * rsc_SAPHanaTopology_PRD_HDB00	(ocf::suse:SAPHanaTopology):	 Started
      * rsc_gcp_stonith_PRD_HDB00_default-hana01	(stonith:fence_gce):	 Started
      * rsc_gcp_vip_PRD_HDB00	(ocf::heartbeat:gcp-vpc-move-route):	 Started
      * rsc_gcp_stonith_PRD_HDB00_default-hana02	(stonith:fence_gce):	 Started
      * rsc_SAPHana_PRD_HDB00	(ocf::suse:SAPHana):	 Master

Inactive Resources:
  * No inactive resources

Migration Summary:
```
```
default-hana01:~ # SAPHanaSR-showAttr 
Global cib-time                 
--------------------------------
global Tue Mar  2 12:46:33 2021 

Resource                      is-managed 
-----------------------------------------
cln_SAPHanaTopology_PRD_HDB00 true       

Sit srHook 
-----------
FRA PRIM   
NUE SOK    

Hosts          clone_state lpa_prd_lpt node_state op_mode   remoteHost     roles                            score site srmode sync_state version                vhost          
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
default-hana01 DEMOTED     30          online     logreplay default-hana02 4:S:master1:master:worker:master 100   NUE  sync   SOK        2.00.046.00.1581325702 default-hana01 
default-hana02 PROMOTED    1614689193  online     logreplay default-hana01 4:P:master1:master:worker:master 150   FRA  sync   PRIM       2.00.046.00.1581325702 default-hana02 
```

**Comment by ab-mohamed** [comment]
@arbulu89: 

I noticed the following messages in the log files:
```
Mar 02 12:29:59 default-hana01 SAPHanaTopology(rsc_SAPHanaTopology_PRD_HDB00)[8865]: INFO: RA ==== end action monitor_clone with rc=0 (0.154.0) (3s)====
Mar 02 12:30:07 default-hana01 /gcp-vpc-move-route[8895]: INFO: IP monitor: checking local network configuration
Mar 02 12:30:07 default-hana01 /gcp-vpc-move-route[8895]: DEBUG: The floating IP 10.0.1.12 is correctly configured on this instance (default-hana01)
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ Traceback (most recent call last): ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [   File "/usr/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [     from google.appengine.api import memcache ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ ModuleNotFoundError: No module named 'google.appengine' ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [  ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ During handling of the above exception, another exception occurred: ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [  ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ Traceback (most recent call last): ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [   File "/usr/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module> ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [     from oauth2client.contrib.locked_file import LockedFile ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file' ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [  ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ During handling of the above exception, another exception occurred: ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [  ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ Traceback (most recent call last): ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [   File "/usr/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module> ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [     from oauth2client.locked_file import LockedFile ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ ModuleNotFoundError: No module named 'oauth2client.locked_file' ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [  ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ During handling of the above exception, another exception occurred: ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [  ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ Traceback (most recent call last): ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [   File "/usr/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [     from . import file_cache ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [   File "/usr/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module> ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [     'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth') ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ INFO:gcp-vpc-move-route:IP monitor: checking local network configuration ]
Mar 02 12:30:07 default-hana01 pacemaker-execd[18414]:  notice: rsc_gcp_vip_PRD_HDB00_monitor_60000[8895] error output [ DEBUG:gcp-vpc-move-route:The floating IP 10.0.1.12 is correctly configured on this instance (default-hana01) ]
```

Any clue?

**Comment by ldevulder** [comment]
@ab-mohamed As I wrote on RocketChat: I have the issue on SLE 15-SP3, not 15-SP2. The `fence_gce` RA is more recent on 15-SP3 and the default stonith method has been changed from `cycle` to `onoff`. No issue with `cycle` method.

Sorry for not mentioning this before!

**Comment by arbulu89** [comment]
@ab-mohamed They look just warning message when the code tries to get some additional modules. All these imports are protected by `try/except`, so they should be optional, but maybe the code is just printing the error.
There are a lot of new changes in that part in the last month in upstream, and they are out of my control. I don't follow which of the versions we are shipping

**Comment by stefanotorresi** [comment]
> I don't follow which of the versions we are shipping

@arbulu89 I think @varkoly and @watologo1 can answer that for you

**Comment by ldevulder** [comment]
So according to [bsc#1182701]( https://bugzilla.suse.com/show_bug.cgi?id=1182701) a PR to revert `fence_gce` method value to the previous `cycle` default one has been made. But it could be a good idea to set this `method=cycle` value in the `fence_gce` primitive configuration? In case of a future change like this, WDYT?

**Comment by ab-mohamed** [comment]
@ldevulder: Thank you for sharing that with us. 
Based on the `fence_gce` documentation using the (`crm ra info stonith:fence_gce` command), I see that the default `method` value is `cycle`. 

Based on https://github.com/ClusterLabs/fence-agents/pull/389/commits/b8793b7cdacf0eb13e86581fcba1f78bb7a4bc13#diff-6b905145430bee60bc020d4bb5649735d281c1e94e5b9f86d8454249cdfcf62dR361, I understand that the default `method` value will be `cycle. Please verify that and if my understanding is right, I think that we may not need to add the default value in the configurations.

@arbulu89 Could you please have a look. 

Best regards,
Ab

**Comment by arbulu89** [comment]
@ab-mohamed If the PR with the change you comment is merged we shouldn't need to specify anything on the agent primitive.

**Comment by ab-mohamed** [comment]
Thanks, @arbulu89.

**Comment by ab-mohamed** [comment]
@watologo1 FYI.

**Comment by stefanotorresi** [comment]
Closing as this has been fixed upstream.

**Pull request closed without merging**
