### PR TITLE
Remove note about tf13 libvirt install

### PR DESCRIPTION
**Pull request by MalloZup**
this is fixed by latest RPM

### CODE REVIEW

**Review by arbulu89 — CHANGES_REQUESTED** [review]
@MalloZup As far as I see now the package is release in /usr/share/terraform/plugins/registry.terraform.io/dmacvicar/libvirt/0.6.3/linux_amd64/terraform-provider-libvirt

This means that we need to change the libvirt files to tell them to use this new version:
https://github.com/SUSE/ha-sap-terraform-deployments/blob/develop/libvirt/infrastructure.tf#L10

This is done in multiple places, search for this line in the whole project.

And besides this, we will need to update our Jenkins workers (out of the scope of this PR). Please sync all the things together

**Comment by MalloZup** [comment]
@arbulu89 yes that PATH was discussed with Terraform upstream etc. is something we endedup to use.

Yop I forgot to update the version.thx!

**Comment by MalloZup** [comment]
thx @arbulu89  I have updated the TF files accordingly

**Review by arbulu89 — APPROVED** [review]
@MalloZup Thanks!
Please, update the package in the jenkins CI machine (or let me know if you have any issue with this)

**Comment by MalloZup** [comment]
@arbulu89 ok will do

**Comment by MalloZup** [comment]
@arbulu89 I'm, taking care with simran on this

**Pull request merged**
