### PR TITLE
fix(prometheus): corosync service not checked

### PR DESCRIPTION
**Pull request by faust64**
cherry-picking commit originally submitted in https://github.com/SUSE/ha-sap-terraform-deployments/pull/679

The pacemaker unit is checked twice. Corosync however, is not checked.

### CODE REVIEW

**Review by arbulu89 — APPROVED** [review]
Thanks @faust64 
Could you rebase `develop` branch so it gets the CI fix commit.
We will merge after that.

**Comment by arbulu89** [comment]
@faust64 I think it is just better if you rebase the the `develop` branch using the command line rather than merging develop all the time. To avoid having that many merge commits

**Comment by faust64** [comment]
Sorry, I'm not much familiar with git rebase. I assumed the update button showing here might just do that ... Apparently not

**Comment by faust64** [comment]
Last commits should be a rebase, if I'm not mistaken, ...  let me know if there's anything else I can do.

**Comment by arbulu89** [comment]
There is not anything wrong on having `merge` commits, but it makes the history ugly.
I would do the next:
1. `git reset --hard HEAD~4` This should move you to your 1st commit of this branch
2. Update upstream. I don't know how you have this configured but usually `git fetch upstream` where upstream is the main fork
(you could create this simply with `git remote add upstream git@github.com:SUSE/ha-sap-terraform-deployments.git` if you don't have it)
3. `git rebase upstram develop`. This should move your commit to the top
4. Push back again. `git push --force origin fix-prometheus-rules-develop`

This should work to have a single commit in the PR without any merge commit

**Comment by faust64** [comment]
Allright, then my commit's gone...

**Comment by faust64** [comment]
I can't re-open. perfect...

**Pull request closed without merging**
